type: com.google.api.codegen.ConfigProto
config_schema_version: 2.0.0
# The settings of generated code in a specific language.
name: cook.gapic.cook.wii.pub
language_settings:
  java:
    package_name: pub.wii.cook.gapic.cook.v1